[package]
name = "bsp_raspi3b1_2"
version = "0.1.0"
edition = "2021"

[dependencies]
aarch64-cpu = { workspace = true }
linked_list_allocator = { workspace = true }
tock-registers = { workspace = true }
