[package]
name = "jam_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bsp_raspi3b1_2 = { path = "./bsp_raspi3b1_2" }

[build-dependencies]
bsp_raspi3b1_2 = { path = "./bsp_raspi3b1_2", features=["builder"] }
