[package]
name = "chainloader-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bsp_raspi3b1_2 = { workspace = true }

[build-dependencies]
bsp_raspi3b1_2 = { workspace = true, features = ["builder"]}
